name: SUperRyzeNS [AOSP]
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: 🕚 Prepare timezone 
      run: |
            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y-%H%M")" >> $GITHUB_ENV
            sudo rm /etc/localtime
            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
        
    - name: ♻️ Install Dependencies
      run: |
            sudo apt update -y
            sudo apt install -y zstd bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 lld llvm
            sudo aptitude install -y libssl-dev
        
    - name: ♻️ Cloning Toolchains 
      run: |
            set -e
            mkdir -p clang
            cd clang
            curl -L --fail --retry 3 \
            -o clang.tar.zst \
            https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/10032024/neutron-clang-10032024.tar.zst
            tar --use-compress-program=unzstd -xvf clang.tar.zst
            cd ..
            git clone https://github.com/greenforce-project/gcc-arm64 -b main --depth=1 gcc64
            git clone https://github.com/greenforce-project/gcc-arm -b main --depth=1 gcc32
            echo "CLANG_PATH=$(pwd)/clang" >> $GITHUB_ENV
            echo "PATH=$(pwd)/clang/bin:$PATH" >> $GITHUB_ENV
            echo "GCC64_PATH=$(pwd)/gcc64" >> $GITHUB_ENV
            echo "GCC32_PATH=$(pwd)/gcc32" >> $GITHUB_ENV

    - name: 🖥️ AOSP Dimension
      run: |
            sed -i 's/qcom,mdss-pan-physical-width-dimension = <695>;$/qcom,mdss-pan-physical-width-dimension = <69>;/' arch/arm64/boot/dts/qcom/dsi-panel-k6-38-0c-0a-fhd-dsc-video.dtsi
            sed -i 's/qcom,mdss-pan-physical-height-dimension = <1546>;$/qcom,mdss-pan-physical-height-dimension = <154>;/' arch/arm64/boot/dts/qcom/dsi-panel-k6-38-0c-0a-fhd-dsc-video.dtsi
    
    - name: 🛡️ Apply NoMount
      run: |
            curl -LSs "https://raw.githubusercontent.com/maxsteeel/nomount/refs/heads/dev/kernel/setup.sh" | bash -
    
    - name: ♻️ Build 🦊SUperRyzeNS
      run: |
           export ARCH=arm64
           export PATH="$CLANG_PATH/bin:$GCC64_PATH/bin:$GCC32_PATH/bin:$PATH"
           export KBUILD_BUILD_USER=slipz
           export KBUILD_BUILD_HOST=SIX
           export KBUILD_COMPILER_STRING="$CLANG_PATH/clang"
           make O=out vendor/sweet_defconfig
           make -j$(nproc --all) O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 \
             CC=clang \
             CLANG_TRIPLE=aarch64-linux-gnu- \
             CROSS_COMPILE=$GCC64_PATH/bin/aarch64-elf- \
             CROSS_COMPILE_ARM32=$GCC32_PATH/bin/arm-eabi-
           mv out/.config out/sweet_defconfig.txt
           
    - name: 📩 Upload defconfig 
      uses: actions/upload-artifact@v4
      with:
        name: defconfig-${{ env.BUILD_TIME }}
        path: out/sweet_defconfig.txt

    - name: ♻️ Fetch AnyKernel3
      run: |
           git clone --depth=1 https://github.com/slipzryzens/anykernel3 -b main AnyKernel3  
           cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
           cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
           cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
           cd AnyKernel3
           zip -r "../SUperRyzeNS-AOSP-${{ env.BUILD_TIME }}.zip" *
                    
    - name: 📩 Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: SUperRyzeNS-AOSP-${{ env.BUILD_TIME }}
        path: AnyKernel3/*

    - name: 💌 Sending to zeNS Telegram Bot
      if: success()
      run: |
        cd AnyKernel3

        ZIP_NAME=SUperRyzeNS-AOSP-${{ env.BUILD_TIME }}.zip
        zip -r9 "$ZIP_NAME" ./*

        CAPTION="✅ <b>Kernel Build Success</b>
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━
        Device          : Redmi Note 10 Pro
        Kernel           : SUperRyzeNS [AOSP]
        Toolchain      : Neutron / Google Clang
        Sender          : zeNS Bot
        Build Time    : ${{ env.BUILD_TIME }}
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        curl -f \
          -F document=@"$ZIP_NAME" \
          -F chat_id=${{ secrets.TG_CHAT_ID }} \
          -F parse_mode=HTML \
          -F caption="$CAPTION" \
          https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendDocument
